# Generated by Django 3.1.7 on 2021-04-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='13', max_length=200)),
                ('pin_number', models.IntegerField(default=13)),
                ('state', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='LED',
        ),
    ]
